on: [push]
jobs:
  First Job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        run: npm i
      - name: Run Tests
        run: npm run test
      - name: Build TS
        run: npm run build
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_KEY }}
          access: 'public'
      - name: Check Publish
        if: steps.publish.outputs.type == 'none'
        run: exit 1
