on: [push]
name: publish-npm
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install
        run: yarn
      - name: Run Tests
        run: yarn test
      - name: Build TS
        run: yarn build
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_KEY }}
          access: 'public'
      - name: Check Publish
        if: steps.publish.outputs.type == 'none'
        run: echo Update your version number
        run: exit 1
